--CHALLENGE

--HOW MANY PAYMENT DID EACH STAFF MEMBER HANDLE AND WHO GETS THE BONUS?
SELECT staff_id, COUNT(payment_id)
FROM payment
GROUP BY staff_id
ORDER BY COUNT(payment_id) DESC

--WHAT IS THE AVG REPLACEMENT COST PER MPAA RATING
SELECT rating, ROUND(AVG(replacement_cost), 2)
FROM film
GROUP BY rating
ORDER BY AVG(replacement_cost) DESC

--WHAT ARE THE CUSTOMER IDS OF THE TOP 5 CUSTOMERS BY TOTAL SPEND
SELECT customer_id, SUM(amount)
FROM payment
GROUP BY customer_id
ORDER BY SUM(amount) DESC
LIMIT 5

--CHALLENGE

--WHAT CUSTOMER_IDS ARE ELIGIBLE FOR PLATINUM STATUS?(>40 TRANSACTION PAYMENTS)
SELECT customer_id, COUNT(payment_date)
FROM payment
GROUP BY customer_id
HAVING COUNT(payment_date) > 40
ORDER BY COUNT(payment_date) DESC

--WHAT ARE THE CUSTOEMR ID OF CUSTOMERS WHO HAVE SPENT MORE THAN $100 IN PAYMENT TRANSACTION WITH OUR STAFF ID 2
SELECT staff_id, customer_id, SUM(amount)
FROM payment
WHERE staff_id = 2
GROUP BY staff_id, customer_id
HAVING SUM(amount) > 100
ORDER BY SUM(amount) DESC